### ISSUE TITLE
Error while indexing (flushing to cpu)

### ISSUE THREAD

**Issue by wpertsch** [terrierteam/pyterrier_colbert#26]
Hey,
I was using the notebook [vaswani.ipynb](https://colab.research.google.com/github/cmacdonald/pyterrier_colbert/blob/main/vaswani.ipynb) and everything worked fine.
I tried to redo the indexing on a given remote machine, and I hope I installed everything needed:
```
absl-py                   1.0.0     
alembic                   1.4.1     
beautifulsoup4            4.10.0    
cachetools                4.2.4     
cbor                      1.0.0     
certifi                   2021.10.8 
charset-normalizer        2.0.9     
chest                     0.2.3     
click                     8.0.3     
cloudpickle               2.0.0     
ColBERT                   0.2.0     
cwl-eval                  1.0.10    
Cython                    0.29.25   
databricks-cli            0.16.2    
deprecation               2.1.0     
dill                      0.3.4     
docker                    5.0.3     
entrypoints               0.3       
faiss-gpu                 1.6.5     
filelock                  3.4.0     
Flask                     2.0.2     
gitdb                     4.0.9     
GitPython                 3.1.24    
google-auth               2.3.3     
google-auth-oauthlib      0.4.6     
greenlet                  1.1.2     
grpcio                    1.42.0    
gunicorn                  20.1.0    
HeapDict                  1.0.1     
idna                      3.3       
ijson                     3.1.4     
importlib-metadata        4.8.2     
ir-datasets               0.5.0     
ir-measures               0.2.3     
itsdangerous              2.0.1     
Jinja2                    3.0.3     
joblib                    1.1.0     
lxml                      4.6.5     
lz4                       3.1.10    
Mako                      1.1.6     
Markdown                  3.3.6     
MarkupSafe                2.0.1     
matchpy                   0.5.5     
mlflow                    1.22.0    
more-itertools            8.12.0    
multiset                  2.1.1     
nptyping                  1.4.4     
numpy                     1.21.4    
oauthlib                  3.1.1     
packaging                 21.3      
pandas                    1.3.5     
patsy                     0.5.2     
pip                       20.0.2    
pkg-resources             0.0.0     
prometheus-client         0.12.0    
prometheus-flask-exporter 0.18.6    
protobuf                  3.19.1    
pyasn1                    0.4.8     
pyasn1-modules            0.2.8     
pyautocorpus              0.1.8     
pyjnius                   1.3.0     
pyndeval                  0.0.2     
pyparsing                 3.0.6     
pyterrier-colbert         0.0.1     
python-dateutil           2.8.2     
python-editor             1.0.4     
python-terrier            0.7.1     
pytrec-eval-terrier       0.5.1     
pytz                      2021.3    
PyYAML                    6.0       
querystring-parser        1.2.4     
regex                     2021.11.10
requests                  2.26.0    
requests-oauthlib         1.3.0     
rsa                       4.8       
sacremoses                0.0.46    
scikit-learn              1.0.1     
scipy                     1.7.3     
sentencepiece             0.1.96    
setuptools                44.0.0    
six                       1.16.0    
sklearn                   0.0       
smmap                     5.0.0     
soupsieve                 2.3.1     
SQLAlchemy                1.4.28    
sqlparse                  0.4.2     
statsmodels               0.13.1    
tabulate                  0.8.9     
tensorboard               2.7.0     
tensorboard-data-server   0.6.1     
tensorboard-plugin-wit    1.8.0     
threadpoolctl             3.0.0     
tokenizers                0.8.1rc1  
torch                     1.10.0    
tqdm                      4.62.3    
transformers              3.0.2     
trec-car-tools            2.5.4     
typing-extensions         4.0.1     
typish                    1.9.3     
ujson                     4.3.0     
urllib3                   1.26.7    
warc3-wet                 0.2.3     
warc3-wet-clueweb09       0.2.5     
websocket-client          1.2.3     
Werkzeug                  2.0.2     
wget                      3.2       
wheel                     0.37.0    
zipp                      3.6.0     
zlib-state                0.1.5 
```

The code I run was:
```python
import faiss
assert faiss.get_num_gpus() > 0

import pyterrier as pt
pt.init()

#rm -rf /content/ARQIndex/

checkpoint="http://www.dcs.gla.ac.uk/~craigm/colbert.dnn.zip"

from pyterrier_colbert.indexing import ColBERTIndexer

indexer = ColBERTIndexer(checkpoint, "/home/colbert_pyterrier/indextest", "colbert_smallindex", chunksize=3)
files = pt.io.find_files("/home/colbert_pyterrier/data/small")
gen = pt.index.treccollection2textgen(files)
indexer.index(gen)
```
I already tested the used data on mentioned colab above. 

This is the error I got:
```
No etc/terrier.properties, using terrier.default.properties for bootstrap configuration.
[Dec 28, 17:29:59] [0] 		 #> Local args.bsize = 128
[Dec 28, 17:29:59] [0] 		 #> args.index_root = /home/colbert_pyterrier/indextest
[Dec 28, 17:29:59] [0] 		 #> self.possible_subset_sizes = [69905]
Some weights of the model checkpoint at bert-base-uncased were not used when initializing ColBERT: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing ColBERT from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing ColBERT from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of ColBERT were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['linear.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
[Dec 28, 17:30:05] #> Loading model checkpoint.
[Dec 28, 17:30:05] #> Loading checkpoint http://www.dcs.gla.ac.uk/~craigm/colbert.dnn.zip
/home/colbert_pyterrier/project_env/lib/python3.8/site-packages/torch/hub.py:513: UserWarning: Falling back to the old format < 1.6. This support will be deprecated in favor of default zipfile format introduced in 1.6. Please redo torch.save() to save it in the new zipfile format.
  warnings.warn('Falling back to the old format < 1.6. This support will be '
[Dec 28, 17:30:13] #> checkpoint['epoch'] = 0
[Dec 28, 17:30:13] #> checkpoint['batch'] = 44500




[Dec 28, 17:30:14] #> Note: Output directory /home/colbert_pyterrier/indextest already exists




[Dec 28, 17:30:14] #> Creating directory /home/colbert_pyterrier/indextest/colbert_smallindex 


[Dec 28, 17:30:55] [0] 		 #> Completed batch #0 (starting at passage #0) 		Passages/min: 14.8k (overall),  16.6k (this encoding),  6486.0M (this saving)
[Dec 28, 17:30:55] [0] 		 [NOTE] Done with local share.
[Dec 28, 17:30:55] [0] 		 #> Joining saver thread.
[Dec 28, 17:30:56] [0] 		 #> Saved batch #0 to /home/colbert_pyterrier/indextest/colbert_smallindex/0.pt 		 Saving Throughput = 864.8k passages per minute.

#> num_embeddings = 1572487
[Dec 28, 17:30:56] #> Starting..
[Dec 28, 17:30:56] #> Processing slice #1 of 1 (range 0..1).
[Dec 28, 17:30:56] #> Will write to /home/colbert_pyterrier/indextest/colbert_smallindex/ivfpq.100.faiss.
[Dec 28, 17:30:56] #> Loading /home/colbert_pyterrier/indextest/colbert_smallindex/0.sample ...
#> Sample has shape (78624, 128)
[Dec 28, 17:30:56] Preparing resources for 2 GPUs.
[Dec 28, 17:30:56] #> Training with the vectors...
[Dec 28, 17:30:56] #> Training now (using 2 GPUs)...
0.6025171279907227
24.62867784500122
0.01384115219116211
[Dec 28, 17:31:21] Done training!

[Dec 28, 17:31:21] #> Indexing the vectors...
[Dec 28, 17:31:21] #> Loading ('/home/colbert_pyterrier/indextest/colbert_smallindex/0.pt', None, None) (from queue)...
[Dec 28, 17:31:21] #> Processing a sub_collection with shape (1572487, 128)
[Dec 28, 17:31:21] Add data with shape (1572487, 128) (offset = 0)..
IndexShards shard 0 select modulo 2 = 0
  IndexIVFPQ size 0 -> GpuIndexIVFPQ indicesOptions=0 usePrecomputed=0 useFloat16=1 reserveVecs=33554432
IndexShards shard 1 select modulo 2 = 1
  IndexIVFPQ size 0 -> GpuIndexIVFPQ indicesOptions=0 usePrecomputed=0 useFloat16=1 reserveVecs=33554432
1507328/1572487 (0.614 s)   Flush indexes to CPU
Traceback (most recent call last):
  File "smallindex.py", line 16, in <module>
    indexer.index(gen)
  File "/home/colbert_pyterrier/project_env/lib/python3.8/site-packages/pyterrier_colbert/indexing.py", line 343, in index
    index_faiss(self.args)
  File "/home/colbert_pyterrier/project_env/lib/python3.8/site-packages/colbert/indexing/faiss.py", line 108, in index_faiss
    index.add(sub_collection)
  File "/home/colbert_pyterrier/project_env/lib/python3.8/site-packages/colbert/indexing/faiss_index.py", line 48, in add
    self.gpu.add(self.index, data, self.offset)
  File "/home/colbert_pyterrier/project_env/lib/python3.8/site-packages/colbert/indexing/faiss_index_gpu.py", line 118, in add
    self._flush_to_cpu(index, nb, offset)
  File "/home/colbert_pyterrier/project_env/lib/python3.8/site-packages/colbert/indexing/faiss_index_gpu.py", line 135, in _flush_to_cpu
    self.gpu_index.sync_with_shard_indexes()
AttributeError: 'IndexShards' object has no attribute 'sync_with_shard_indexes'

```
What went wrong?
Thank you for your help and sorry for the long print.
Kind regards

**Comment by cmacdonald** [comment]
I havent seen this specific error, but tis is some kind of Faiss error. I would recommend re-installing Faiss. If you installed Faiss using pip, this could be the problem - the Faiss people will tell you that only Conda is supported

**Comment by wpertsch** [comment]
We managed to install pyterrier_colbert without conda and create an index using the default checkpoint.
The data we indexed was XML in TREC-format.
The installation looked like this:
```
pip install python-terrier
pip install wheel
pip install faiss-gpu==1.6.3
pip install --upgrade git+https://github.com/terrierteam/pyterrier_colbert.git
```
The code we used was the same as above, except ```ids=false``` on the ColBERTIndexer:
```python
import faiss
assert faiss.get_num_gpus() > 0

import pyterrier as pt
pt.init()

checkpoint="http://www.dcs.gla.ac.uk/~craigm/colbert.dnn.zip"

from pyterrier_colbert.indexing import ColBERTIndexer

indexer = ColBERTIndexer(checkpoint, "/home/exampleforgithub/indextest", "colbert_smallindex", chunksize=3, ids=False)
files = pt.io.find_files("/home/exampleforgithub/data/small")
gen = pt.index.treccollection2textgen(files)
indexer.index(gen)
print("well done index")

```
